# Site settings
title: weijuner
email: weijuner.email@qq.com
description: "Python,HTML,CSS,Machine Leaning"
permalink: /:year/:month/:day/:title.html
baseurl: ""
url: "http://weijuner.com"
atom-baseurl: "http://weijuner.com"
author: "weijuner"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : taizilongxu

navigations:
  - title: 关于
    class: fa fa-list-ul
    href: /about/
  - title: 文字
    class: fa fa-tags
    href: /archive/
  - title: 分类
    class: fa fa-user
    href: /categories/
  - title: 标签
    class: fa fa-film
    href: /tags/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
